DROP TABLE IF EXISTS item CASCADE;
DROP TABLE IF EXISTS event CASCADE;
DROP TABLE IF EXISTS feedback CASCADE;
DROP TABLE IF EXISTS member CASCADE;
DROP TABLE IF EXISTS member_role CASCADE;
DROP TABLE IF EXISTS member_event CASCADE;


-- Sample
CREATE TABLE IF NOT EXISTS item (
                                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                    text varchar(255) NOT NULL,
                                    done BOOLEAN
);

-- Create tables
CREATE TABLE IF NOT EXISTS event (
                                     event_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     event_title VARCHAR,
                                     event_date TIMESTAMP,
                                     attendance_type TEXT,
                                     comment TEXT,
                                     helpers_needed INT
);

CREATE TABLE IF NOT EXISTS feedback (
                                        feedback_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                        event_id BIGINT NOT NULL,
                                        comment TEXT,
                                        FOREIGN KEY (event_id) REFERENCES event(event_id)
);

CREATE TABLE IF NOT EXISTS member (
                                      member_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                      first_name VARCHAR NOT NULL,
                                      last_name VARCHAR NOT NULL,
                                      birthday TIMESTAMP,
                                      phone VARCHAR,
                                      email VARCHAR,
                                      points INT,
                                      password VARCHAR
);

CREATE TABLE IF NOT EXISTS member_role (
                                           member_role_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                           member_id BIGINT NOT NULL,
                                           member_level INT,
                                           FOREIGN KEY (member_id) REFERENCES member(member_id)
);

CREATE TABLE IF NOT EXISTS member_event (
                                            member_event_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                            event_id BIGINT NOT NULL,
                                            member_receiver_id BIGINT NOT NULL,
                                            member_manager_id BIGINT NOT NULL,
                                            task TEXT,
                                            points INT,
                                            FOREIGN KEY (event_id) REFERENCES event(event_id),
                                            FOREIGN KEY (member_receiver_id) REFERENCES member(member_id),
                                            FOREIGN KEY (member_manager_id) REFERENCES member(member_id)
);
