CREATE TABLE IF NOT EXISTS item (
                                    id INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 10) PRIMARY KEY,
                                    text varchar(255) NOT NULL,
                                    done BOOLEAN
);

