CREATE TABLE IF NOT EXISTS item (
                                    id INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 10) PRIMARY KEY,
                                    text varchar(255) NOT NULL,
                                    done BOOLEAN
);


-- Create tables
CREATE TABLE IF NOT EXISTS event (
                                     event_id SERIAL PRIMARY KEY,
                                     event_title VARCHAR,
                                     date DATE,
                                     attendance_type TEXT,
                                     comment TEXT,
                                     helpers_needed INT
);

CREATE TABLE IF NOT EXISTS feedback (
                                        feedback_id SERIAL PRIMARY KEY,
                                        event_id INT NOT NULL,
                                        comment TEXT,
                                        FOREIGN KEY (event_id) REFERENCES event(event_id)
);

CREATE TABLE IF NOT EXISTS member (
                                      member_id SERIAL PRIMARY KEY,
                                      name VARCHAR NOT NULL,
                                      birthday DATE,
                                      phone VARCHAR,
                                      email VARCHAR,
                                      points INT
);

CREATE TABLE IF NOT EXISTS member_role (
                                           member_role_id SERIAL PRIMARY KEY,
                                           member_id INT NOT NULL,
                                           member_level INT,
                                           FOREIGN KEY (member_id) REFERENCES member(member_id)
);

CREATE TABLE IF NOT EXISTS member_event (
                                          member_event_id SERIAL PRIMARY KEY,
                                          event_id INT NOT NULL,
                                          member_receiver_id INT NOT NULL,
                                          member_manager_id INT NOT NULL,
                                          task TEXT,
                                          points INT,
                                          FOREIGN KEY (event_id) REFERENCES event(event_id),
                                          FOREIGN KEY (member_receiver_id) REFERENCES member(member_id),
                                          FOREIGN KEY (member_manager_id) REFERENCES member(member_id)
);